### PR TITLE
Delete unused build.rs

### PR DESCRIPTION
**Pull request by AndreyErmilov**
We use musl to build the project and we had an error compiling diesel migrations. Build.rs is not used in .travis.ci, but it runs by default when the package is built.

Please see pull request :)

### CODE REVIEW

**Comment by kivikakk** [comment]
LGTM — thanks! Let me know if you want a new release.

**Comment by AndreyErmilov** [comment]
@kivikakk Thanks! Yep, make a new release, please :)

**Comment by kivikakk** [comment]
Done! `0.2.2` is on [crates.io](https://crates.io) now: https://crates.io/crates/diesel_ltree.

**Comment by AndreyErmilov** [comment]
> Done! `0.2.2` is on [crates.io](https://crates.io) now: https://crates.io/crates/diesel_ltree.

Thanks a lot!

**Pull request merged**
